### ISSUE TITLE
Streaming very bad 3D video quality

### ISSUE THREAD

**Issue by XimingCheng** [adamrehn/pixel-streaming-linux#13]
Hi, thanks for this good Linux pixel-streaming demo, I have run this demo successfully on my own Ubuntu PC, but when I stream the rending ue4 3D dummy project, I have found the video quality is very bad, lots of blocks artifact and mosaic on the video. When I check the video bitrate, I found that it is very high bitrate which seems not the video encoding target bitrate setting error.
![image](https://user-images.githubusercontent.com/2611722/86871497-fad12400-c10c-11ea-9ce5-9043572295c7.png)
The bad video quality can be found when mouse move. Could help me to find where to set the rending video quality? Thanks!
![image](https://user-images.githubusercontent.com/2611722/86871906-bdb96180-c10d-11ea-9c38-2d433fe01674.png)

**Comment by adamrehn** [comment]
Hmm, strange. I don't have a lot of experience tweaking the advanced video quality parameters, but I'd suggest experimenting with the [Console Commands and Command-Line Parameters](https://docs.unrealengine.com/en-US/Platforms/PixelStreaming/PixelStreamingReference/index.html#unrealengineconsolecommands) listed in the official Pixel Streaming documentation as a good starting point.

**Comment by XimingCheng** [comment]
I add `-NvEncFrameRateNum=1` to solve this problem, but it is confused to me to understand why this low nvencode encode frame rate will reduce the blocks artifact and mosaic on the video.

**Comment by salanki** [comment]
I'm seeing the same with default settings. Fixed by setting `-NvEncFrameRateNum=1 `.
![pixelstream](https://user-images.githubusercontent.com/192223/88008482-5f618b00-cade-11ea-904b-f4104f55c893.gif)
