### ISSUE TITLE
Stuck on "Checking Pak Config"

### ISSUE THREAD

**Issue by xxjunxx** [adamrehn/pixel-streaming-linux#20]
After I built the image successfully using the demo dummy project, I tried to run the container with command `sudo docker run --gpus all --rm -it  xj/ue-run --network=host`. And I got the following logging,  it just stuck on "Checking Pak Config". Do you have any idea what could be the reason？

```
4.23.1-8386587+++UE4+Release-4.23 517 0
Disabling core dumps.
sh: 1: xdg-user-dir: not found
error: XDG_RUNTIME_DIR not set in the environment.
Unable to read VR Path Registry from /home/ue4/.config/openvr/openvrpaths.vrpath
Unable to read VR Path Registry from /home/ue4/.config/openvr/openvrpaths.vrpath
Checking Pak Config
```

**Comment by avg07** [comment]
I have same issue after packaging project from ue-4.23.1 and run image:
```
FROM adamrehn/ue4-full:4.23.1-pixelstreaming AS builder
COPY --chown=ue4:ue4 ./DummyProject /tmp/project
WORKDIR /tmp/project
RUN ue4 package
FROM adamrehn/ue4-runtime:latest
COPY --from=builder --chown=ue4:ue4 /tmp/project/dist/LinuxNoEditor /home/ue4/project
ENV NVIDIA_DRIVER_CAPABILITIES ${NVIDIA_DRIVER_CAPABILITIES},video
RUN ln -s /usr/lib/x86_64-linux-gnu/libnvidia-encode.so.1 /home/ue4/project/DummyProject/Binaries/Linux/libnvidia-encode.so.1
```
I'm trying to docker-run like this:
`sudo docker run --network=host --gpus=all -v /tmp/.X11-unix:/tmp/.X11-unix:rw -e DISPLAY ue4-test:13 bash -c "/home/ue4/project/MyProject3.sh -PixelStreamingIP=localhost -PixelStreamingPort=8888 -opengl4"`

But recive error:
```
sh: 1: xdg-user-dir: not found
error: XDG_RUNTIME_DIR not set in the environment.
Unable to read VR Path Registry from /home/ue4/.config/openvr/openvrpaths.vrpath
Unable to read VR Path Registry from /home/ue4/.config/openvr/openvrpaths.vrpath
Checking Pak Config
Signal 11 caught.
Malloc Size=65538 LargeMemoryPoolOffset=65554 
Malloc Size=65535 LargeMemoryPoolOffset=131119 
Malloc Size=123824 LargeMemoryPoolOffset=254960 
4.23.1-8386587+++UE4+Release-4.23 517 0
Disabling core dumps.
CommonUnixCrashHandler: Signal=11
Engine crash handling finished; re-raising signal 11 for the default handler. Good bye.
Segmentation fault (core dumped)
```

**Comment by adamrehn** [comment]
@avg07 the "problem" in the original post is not in fact a problem at all, it is simply the log output that is displayed when successfully running a Pixel Streaming project packaged in the Shipping build configuration (and presumably the original poster realised this, given that they closed the issue without further comment.) Your problem is different and is an actual error, since your packaged project is crashing with a segmentation fault. Could you please re-package your project in the Development build configuration (which will display full log output) and post the output here?

**Comment by adamrehn** [comment]
Nevermind, I see that you've opened a separate issue (#25), so I'll continue this thread there.
