### ISSUE TITLE
Unable to send double click events from PixelStreaming

### ISSUE THREAD

**Issue by musigmaindlabs** [adamrehn/pixel-streaming-linux#22]
I have an issue. I am unable to send a double-click event from pixel streaming. Consider I have an object which needs to double-clicked for collapsing it works in a packaged game(Executable) but not via pixel streaming.

I went through the inputdevice.cpp file for PixelStreaming and there is no event written for double click. Can someone help please

**Comment by adamrehn** [comment]
This issue tracker is for discussing issues specific to the Linux port of Pixel Streaming. Issues related to Pixel Streaming in general (i.e. those that affect the original Windows version as well) should be reported directly to Epic Games.
