### ISSUE TITLE
Fix how Unreal searches for system level dynamic libraries (libnvidia-encode.so)

### ISSUE THREAD

**Issue by lukehb** [adamrehn/pixel-streaming-linux#26]
Currently Unreal Engine fails to find libnvidia-encode.so (which is installed system wide by the NVIDIA driver) and must have it symlinked into the binaries folder of either the editor or the packaged project before being able to use the Pixel Streaming plugin.

There is probably some pathing issues in the Linux implementation of `FPlatformProcess::GetDllHandle` that could be fixed to remove this requirement.

**Comment by bcizmeci** [comment]
Is the following assertion failed error related to this issue?

Assertion failed: Result == NV_ENC_SUCCESS [File:/home/heapvrar/git/UnrealEngine/Engine/Plugins/Media/PixelStreaming/Source/CudaVideoEncoder/Private/CudaVideoEncoder.cpp] [Line: 448] Unable to open NvEnc encoding session (status: 15)

**Comment by lukehb** [comment]
@ImmortalEmperor ^^

**Comment by lukehb** [comment]
This has been fixed in: https://github.com/ImmortalEmperor/UnrealEngine/commit/c135e9c03f6f161333c7632b234ea84410dd6277
