### ISSUE TITLE
Problems running Linux Pixel streaming when packaged as shipping.

### ISSUE THREAD

**Issue by lcdlv** [adamrehn/pixel-streaming-linux#33]
I have working UE4 with my Laptop in Ubuntu 20.04.
I open my project and hit PLAY STANDALONE everything works fine, even Pixel Streaming locally.
But, the game won't start after export for Linux with the default Setting in Project Setting.
I typed in a terminal "./VSHOP_310120.sh" and first I was having this error:

LowLevelFatalError [File:Unknown] [Line: 75] No CUDA Interop capable GPU found with UUID ₻ꁪ뿷暧渎㎏࿩⥧탈구軈硰鎨暶覚. 0x00000000023cb13f VSHOP_310120-Linux-Shipping!UnknownFunction(0x21cb13e) 0x00000000022c2379 VSHOP_310120-Linux-Shipping!UnknownFunction(0x20c2378) 0x00000000022bf645 VSHOP_310120-Linux-Shipping!UnknownFunction(0x20bf644) 0x00000000022c225c VSHOP_310120-Linux-Shipping!UnknownFunction(0x20c225b) 0x0000000005076b7d VSHOP_310120-Linux-Shipping!UnknownFunction(0x4e76b7c) 0x00007fb14df2d0b3 libc.so.6!__libc_start_main(+0xf2) 0x00000000022bf029 VSHOP_310120-Linux-Shipping!UnknownFunction(0x20bf028)

VSHOP_310120-Linux-Shipping!UnknownFunction(0x27c916e)
VSHOP_310120-Linux-Shipping!UnknownFunction(0x28d1636)
VSHOP_310120-Linux-Shipping!UnknownFunction(0x21cadce)
VSHOP_310120-Linux-Shipping!UnknownFunction(0x21cb13e)
VSHOP_310120-Linux-Shipping!UnknownFunction(0x20c2378)
VSHOP_310120-Linux-Shipping!UnknownFunction(0x20bf644)
VSHOP_310120-Linux-Shipping!UnknownFunction(0x20c225b)
VSHOP_310120-Linux-Shipping!UnknownFunction(0x4e76b7c)
libc.so.6!__libc_start_main(+0xf2)
VSHOP_310120-Linux-Shipping!UnknownFunction(0x20bf028)

Later, touching things, the error change and now I have this error in the Terminal:

4.25.4-0+++UE4+Release-4.25 518 0
Disabling core dumps.
INTEL-MESA: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

X Error of failed request:  BadDrawable (invalid Pixmap or Window parameter)
  Major opcode of failed request:  149 ()
  Minor opcode of failed request:  4
  Resource id in failed request:  0x2400041
  Serial number of failed request:  372
  Current serial number in output stream:  383
terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument
Signal 6 caught.
Segmentation fault (core dumped)

This is my NVIDIA-SMI:

Thu Feb 18 19:31:46 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 2060    On   | 00000000:01:00.0 Off |                  N/A |
| N/A   63C    P8     8W /  N/A |    361MiB /  5934MiB |      5%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1005      G   /usr/lib/xorg/Xorg                251MiB |
|    0   N/A  N/A      1388      G   /usr/bin/gnome-shell               38MiB |
|    0   N/A  N/A      7082      G   ...gAAAAAAAAA --shared-files       37MiB |
|    0   N/A  N/A     11932      G   ...AAAAAAAA== --shared-files       31MiB |
+-----------------------------------------------------------------------------+

What I'm doing wrong?

**Comment by ImmortalEmperor** [comment]
Have you configured some kind of GPU selection thing (like bumblebee)? Or are you running on battery? It seems to have started the engine's RHI with the Intel integrated graphics card (which will run Vulkan) and return it's UUID but is being rejected because it cannot run CUDA on that GPU. There should be a flag that you can pass to the game to preference a GPU if its not something you've changed OS wide.

**Comment by lcdlv** [comment]
I tryed to use Bumblebee but first had errors, and then I fix that but running optirun MYAPP nothing happended...
I used sudo prime-select nvidia to use NVIDIA card, but I get the same error running the app. 
The problem is there: how to run the game with the NVIDIA card. When I open Unreal Editor, the STAND ALONE works because it's coming using the NVIDIA card already.

**Comment by lcdlv** [comment]
I not a linux user, so I'm discovering everything on the way.

**Comment by lukehb** [comment]
Additionally, can you re-package your project in development instead of shipping so we can get more verbose log output and then post that log output here?

**Comment by lcdlv** [comment]
Hi Luke! I solved it. Packaging in Shipping gives the error I mentioned, but in Development works fine!!! That´s crazy, but I can rest now!
When you make a AWS machine to run the game and the server at the same time, you install a GUI and do all using that. or just use -norenderscreen in a text mode and thats all?

**Comment by lukehb** [comment]
> Packaging in Shipping gives the error I mentioned, but in Development works fine!!!

Okay, nice find. We will test packaging with `Shipping` to see if we can reproduce the issue and begin solving.

> When you make a AWS machine to run the game and the server at the same time, you install a GUI and do all using that. or just use -norenderscreen in a text mode and thats all?

Not sure if I understand the question exactly, but if the question is whether you can install server and game using GUI or cli, cli is fine and the game can render offscreen using `-RenderOffScreen`.

**Comment by lcdlv** [comment]
Using a Ubuntu 20.04 with NICE DVC and GPU acelerated Vulkan works fine (packaaged in Developer) and I can run the game, and the server and watch it locally.

https://aws.amazon.com/marketplace/pp/prodview-2uxmksr7nwzkw?ref_=unifiedsearch

You can close the issue.
