### ISSUE TITLE
CUDA fails to initialise in Shipping configuration

### ISSUE THREAD

**Issue by adamrehn** [adamrehn/pixel-streaming-linux#37]
Although Pixel Streaming functions correctly in projects that have been packaged in the Development build configuration, projects built in the Shipping configuration encounter the following error:

```
LowLevelFatalError [File:Unknown] [Line: 75] 
No CUDA Interop capable GPU found with UUID 쫍Ḳ鲨䞃䚭㳋᧔갋⠒攋㯂硋허꽰.
```

@ImmortalEmperor this is happening inside your CUDA module, please investigate.

**Comment by luc122c** [comment]
Hi @adamrehn, I'm getting the following error:
`/home/ue4/project/PixelStreamingTest/Binaries/Linux/PixelStreamingTest: error while loading shared libraries: libcuda.so.1: cannot open shared object file: No such file or directory`
Is this related to the same issue, or should I open a new one?

**Comment by adamrehn** [comment]
@luc122c that error is unrelated and typically indicates that you either have not used a container image that includes the CUDA runtime, or have forgotten to specify `--gpus=all` when starting the container. If you are using a correctly configured container image and have started it using the required flags then I'd recommend opening a separate issue to discuss your error.

**Comment by luc122c** [comment]
@adamrehn Thanks, It turns out that my Docker Compose file wasn't correct so it wasn't requesting gpus. Now that it is, I'm having the same issue as above. The workaround of building for Development works though. Thanks again :)

**Comment by lukehb** [comment]
Pixel Streaming for Linux 4.25 now builds in shipping, see commit [here](https://github.com/ImmortalEmperor/UnrealEngine/commit/7ba6faefb6f4252a8991c5df5be9cd2df061b633).
