### ISSUE TITLE
AWS ECS deployment, unable to open libnvidia-glvkspirv

### ISSUE THREAD

**Issue by luc122c** [adamrehn/pixel-streaming-linux#43]
Hi There, I'm having a similar issue to #30 on AWS. I'm using Docker Compose to deploy my 4.25 application to an ECS cluster. The CloudFormation template uses the 'AWS Deep Learning AMI (Ubuntu 18.04)' on a `g4dn.xlarge` instance. UE4 is crashing with the following error: `The NVIDIA driver was unable to open 'libnvidia-glvkspirv.so.460.32.03'. This library is required at run time.`.

When I manually create an EC2 instance with the same settings and go to `/usr/lib/x86_64-linux-gnu/`, the driver is there. When I manually run the image on that server, it runs fine, however when I deploy it through ECS, it doesn't seem to load the driver correctly.  Here are the workarounds i've tried:

- Using the EC2 user data to install Vulkan on the instance when it is created
- Symlinking the driver into the `Binaries/Linux` directory in a similar fashion to the `libnvidia-encode` workaround

I understand that it's likely not an issue with this project, however I was wondering if anyone else had come across the same issue or had any ideas? If you're aware of a more appropriate place to ask, please let me know.

Project built with ue4-docker: `build -v --no-engine custom:4.25-pixelstreaming --cuda=10.2 -repo=https://github.com/ImmortalEmperor/UnrealEngine.git -branch=4.25-pixelstreaming`
Runtime: `adamrehn/ue4-runtime:18.04-cudagl10.2`

**Comment by lukehb** [comment]
We haven't tried it in ECS yet to be entirely honest. If you do find a workaround please share it here!

**Comment by luc122c** [comment]
As a workaround, I've performed the following steps to get the application running:

- Download [the driver](https://www.nvidia.com/download/driverResults.aspx/168347/en-us)
- Extract the files from the .run `sh NVIDIA-Linux-x86_64-460.32.03.run -x`
- Copied the driver into the driver directory as root `COPY ./NVIDIA-Linux-x86_64-460.32.03/libnvidia-glvkspirv.so.460.32.03 /usr/lib/x86_64-linux-gnu/libnvidia-glvkspriv.so.460.32.03`
- Symlinked it to the project the same way as the NVENC driver `RUN ln -s /usr/lib/x86_64-linux-gnu/libnvidia-glvkspriv.so.460.32.03  /home/ue4/project/${PROJECT_NAME}/Binaries/Linux/libnvidia-glvkspriv.so.460.32.03`

**Comment by luc122c** [comment]
It seems to be an issue with the specific AMI. See [commend here](https://github.com/aws/amazon-ecs-agent/issues/2835#issuecomment-818281605). NVIDIA have also updated their drivers recently so hoping for a new AMI image soon. Will post back here when I manage to get it working.
