### ISSUE TITLE
How to run unreal engine pixel streaming on linux

### ISSUE THREAD

**Issue by agavrel** [adamrehn/pixel-streaming-linux#48]
Thank you very much for your project. In your youtube video you run PixelStreamingDemo.sh https://www.youtube.com/watch?v=tcGJMiPxq5A 0:28

However I am having trouble with this part, what is contained in the .sh ? How to run it on Linux?

**Comment by lukehb** [comment]
The .sh file you are referring to is script created by Unreal Engine when you package Unreal Engine projects under Linux. For example, if your project was called "FunShooterGame", packaging it on Linux would produce FunShooterGame.sh and a bunch of other files. This .sh script is used to launch the Unreal Engine application under Linux. This is roughly analogous to under Windows you may have a .bat file that starts a .exe of your Unreal Engine application.

I will also mention that the video you linked is for the Unreal Engine 4.23 version of Pixel Streaming, there is more updated version, with updated instructions we did for 4.25 here:

https://github.com/ImmortalEmperor/UnrealEngine/tree/4.25-pixelstreaming
