### ISSUE TITLE
Can epic take this version of pixel streaming and make it native in the engine ?

### ISSUE THREAD

**Issue by MohamedAliRashad** [adamrehn/pixel-streaming-linux#49]
I noticed that there is no Pull Requests tab on the unreal repository, so is it possible for Linux to be nativily supported ?

**Comment by lukehb** [comment]
As part of 4.27 Epic are planning to support Linux Pixel Streaming: https://portal.productboard.com/epicgames/1-unreal-engine-public-roadmap/c/319-pixel-streaming-now-production-ready

**Comment by Synoecium** [comment]
Does supporting Linux Pixel Streaming work in 4.27 preview?

**Comment by lukehb** [comment]
This official 4.27 release will support Linux Pixel Streaming (it is on the roadmap). However, the 4.27 previews do not yet support it.
