### ISSUE TITLE
PixelStreaming: Error: Failed to initialize Pixel Streaming plugin because Nvidia NVENC was not installed

### ISSUE THREAD

**Issue by SimonLeeGit** [adamrehn/pixel-streaming-linux#5]
Hi, 
     i'm trying to test the PixelStreaming in linux platform. I do everything follow the doc. But, the packaged unreal project throw a error:

**"PixelStreaming: Error: Failed to initialize Pixel Streaming plugin because Nvidia NVENC was not installed"**

I have checked the env (**NVIDIA_DRIVER_CAPABILITIES**) and create the soft link:

`ln -s /usr/lib/x86_64-linux-gnu/libnvidia-encode.so.1 /home/ue4/project/ProjectName/Binaries/Linux/libnvidia-encode.so.1`

1. start container: nvidia-docker run -itd adamrehn/ue4-runtime:latest
2. copy my build package to running container
3. update env NVIDIA_DRIVER_CAPABILITIES
4. create soft link for libnvidia-encode.so.1

Do you know what's the problem ?

**Comment by adamrehn** [comment]
The `NVIDIA_DRIVER_CAPABILITIES` environment variable is read by the underlying NVIDIA container runtime when the container starts, so modifying it once the container is already running will have no effect. You'll need to create a Dockerfile to build an image that extends the ue4-runtime image with the necessary configuration, as per [the example in the documentation](https://adamrehn.com/articles/pixel-streaming-in-linux-containers/#building-container-images).

**Comment by SimonLeeGit** [comment]
Thanks, i'll have a try.
