### ISSUE TITLE
What are the meanings of the turnserver and stunserver parameters in WebRTC release binary?

### ISSUE THREAD

**Issue by slnh312** [adamrehn/pixel-streaming-linux#6]
As mentioned in the title, what are the parameters of the stunserver turnserver command?
```
docker@ue4-docker:~/webrtc/bin$ ./turnserver
usage: turnserver int-addr ext-ip realm auth-file
docker@ue4-docker:~/webrtc/bin$ ./stunserver 
usage: stunserver address
```

**Comment by adamrehn** [comment]
I have no idea, those tools are part of the WebRTC SDK and I've never used them myself. I'd recommend either asking the WebRTC SDK developers for clarification or else reading through the source code of the tools yourself:

- https://webrtc.googlesource.com/src.git/+/547e3169d9e059117de6a22f34c6e959707598e7/examples/stunserver/stunserver_main.cc

- https://webrtc.googlesource.com/src.git/+/547e3169d9e059117de6a22f34c6e959707598e7/examples/turnserver/turnserver_main.cc
